#######################################################
############CONNECTION POOL PROPERTIES#################
#######################################################
port:2426
#######################################################
jdbcDriver:com.microsoft.sqlserver.jdbc.SQLServerDriver
#######################################################
dbUrl:jdbc:sqlserver://127.0.01;databaseName=Ramesh
#######################################################
dbUsername:sa
#######################################################
dbPassword:admin@321
#######################################################
initialConn:5
#######################################################
incrementalConn:3
#######################################################
maxConn:10
#######################################################
maxTimeWait:5000
#######################################################
spName:Commserver_Android
#######################################################
alertSpname:Commserver_Android
#######################################################
validationQuery:select top 1 id from dataout
#######################################################