#######################################################
###############CONNECTION PROPERTIES###################
#######################################################
port:2426
#######################################################
jdbcDriver:com.microsoft.sqlserver.jdbc.SQLServerDriver
#######################################################
dbUrl:jdbc:sqlserver://202.138.98.173;databaseName=sun
#######################################################
dbUsername:sa
#######################################################
dbPassword:Victory99
#######################################################
initialConn:11
#######################################################
incrementalConn:5
#######################################################
maxConn:100
#######################################################
spname:demo
#######################################################